#%RAML 1.0
title: salesforceapi
version: v1
protocols:
  - HTTP
mediaType: 
- application/json


/checkin:
  post:
    body:
      application/json:
        example:
    responses:
            200:
                    body:
                            application/json:
                                    example:
                                                  
